---
dist: xenial
language: ruby
rvm:
- 2.6.6
sudo: false
cache: bundler
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
addons:
  postgresql: '10'
install: bin/setup
after_script: bundle exec codeclimate-test-reporter
