vmware_cloud:
  host: vmwarecloudhost
  userid: VMWARE_CLOUD_USERID
  password: VMWARE_CLOUD_PASSWORD
vmware_infra:
  hostname: HOSTNAME
vmware_tanzu:
  hostname: vmware-tanzu-hostname
  userid: VMWARE_TANZU_USERID
  password: VMWARE_TANZU_PASSWORD
