#!/usr/bin/env ruby

require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "manageiq-loggers", "~>1.0"
  gem "manageiq-messaging", "~> 1.0"
  gem "rbvmomi2", "~> 3.3"
  gem "sd_notify"
  gem "json"
end

require_relative "event_catcher"

def setproctitle
  proc_title = "MIQ: Vmware::InfraManager::EventCatcher guid: #{ENV.fetch("GUID", nil)}"
  Process.setproctitle(proc_title)
end

def build_logger
  ManageIQ::Loggers::Base.new($stdout) # TODO: build container/journal/base logger
end

def main(args)
  setproctitle

  logger         = build_logger
  ems            = args["ems"].detect { |e| e["type"] == "ManageIQ::Providers::Vmware::InfraManager" }
  messaging      = args["messaging"].symbolize_keys
  endpoint       = ems["endpoints"].detect { |ep| ep["role"] == "default" }
  authentication = ems["authentications"].detect { |auth| auth["authtype"] == "default" }

  EventCatcher.new(ems, endpoint, authentication, messaging, logger).run!
end

def parse_args
  JSON.parse($stdin.read)
rescue JSON::ParserError
  abort("Invalid argument format")
end

main(parse_args)
